version: '3'

services:
  painterbot:
    container_name: painterbot
    env_file:
      - .env
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/painterbot
#      - /painterbot/.git
    command: >
      sh -c "
        echo https://${GH_AUTH}:x-oauth-basic@github.com > ~/.git-credentials &&
        python3 -m pip install -e . &&
        python3 /painterbot/src/painterbot/__main__.py
      "
