version: '3'

services:
  painterbot:
    container_name: painterbot
    env_file:
      - .env
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/painterbot
      - /painterbot/.git
    command: >
      sh -c "
        ls -la &&
        python -m pip install -e . &&
        python /painterbot/src/painterbot/__main__.py
      "
